version: '3.8'

services:
  db:
    image: postgres:15
    container_name: replication_db
    restart: always
    environment:
      POSTGRES_USER: user_silex
      POSTGRES_PASSWORD: password_silex
      POSTGRES_DB: silex_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: